### ISSUE TITLE
How can I increase libnetconf2 response timeout?

### ISSUE THREAD

**Issue by igortern** [CESNET/libnetconf2#206]
Hi,
When debugging sysrepo client with all debugs on, it sometimes takes more that 1s to finish edit-config transaction. It appears that there is some timeout in libnetconf2/netopeer2 - the max time it waits for all callbacks to finish before sending RPC response. 
It gives up with error message
[ERR]: LN: Session 1: failed to write reply.
Could you advice what constant controls this timeout? Is it possible to increase it programmatically to avoid patching the sources?
Regards,
Igor

**Comment by michalvasko** [comment]
Hi,
do you maybe have some more output? It should be printed what timeout elapses. Also, I have noticed one return check was not updated and it could have caused an invalid message to be printed, so please update *libnetconf2* (`devel`) and try again.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
I updated everything from devel and still can reproduce the problem. What debug level should I enable to give more information? 
I tried with -c SYSREPO and with -v3 
There is nothing suspicious before the error..
[INF]: LY: There is no instance of "/ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/client-authentication/users", but it is not required.
[INF]: LY: There is no instance of "/ietf-netconf-server:netconf-server/listen/idle-timeout", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 1.
[INF]: SR: Finished processing "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[ERR]: LN: Session 1: failed to write reply.

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
could you please try again? I have improved the messages a bit so you should at least see whether it really time-outed. But the only relevant timeout I found is in [netopeer2](https://github.com/CESNET/Netopeer2/blob/master/server/main.c#L892) and is set to `0` so I am a bit confused.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
After taking today's snapshots I can get to the point this timeout happens. 
Now it fails earlier with NACM authorization error (below). It is a new behaviour. Do I need to add some configuration to get past this error?

Thanks,
Igor

[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:copy-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
**[ERR]: SR: Access to the data model "ietf-netconf-server" is denied because "igort" NACM authorization failed.**
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: NP: Session 1: thread 1 event reply error.

**Comment by michalvasko** [comment]
Hi,
I have just implemented a bugfix for `copy-config`. Just to make sure, what datastores are you using, copying configuration from which datastore to what datastore?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

copy-config target is "running". The source is configuration in RPC message.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
then it will probably be a result of some older changes. Most importantly, is the error correct? Are there any `ietf-netconf-server` data in the configuration you got from the RPC?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

network manager issues the following RPC in order to reset the relevant
tables. Note that it doesn't touch ietf-netconf-server, but does reset
ietf-netconf-acm.
The error reply is still present as of today (see netopeer2-server log
after copy-config). Generally speaking, is it possible to disable nacm in
netopeer2-server? I don't need it for the PoC I'm doing.

Thanks,
Igor

  <copy-config>
    <target>
      <running/>
    </target>
    <source>
      <config>
        <bbf-qos-filt:filters
xmlns:bbf-qos-filt="urn:bbf:yang:bbf-qos-filters"/>
        <bbf-lt:link-table xmlns:bbf-lt="urn:bbf:yang:bbf-link-table"/>
        <ipfix:ipfix
xmlns:ipfix="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp"/>
        <hw:hardware xmlns:hw="urn:ietf:params:xml:ns:yang:ietf-hardware"/>
        <bbf-qos-cls:classifiers
xmlns:bbf-qos-cls="urn:bbf:yang:bbf-qos-classifiers"/>
        <pw:pseudowires
xmlns:pw="urn:ietf:params:xml:ns:yang:ietf-pseudowires"/>
        <bbf-xpon:xpon xmlns:bbf-xpon="urn:bbf:yang:bbf-xpon"/>
        <bbf-ghn:ghn xmlns:bbf-ghn="urn:bbf:yang:bbf-ghn"/>
        <bbf-qos-pol:qos-policy-profiles
xmlns:bbf-qos-pol="urn:bbf:yang:bbf-qos-policies"/>
        <al:alarms xmlns:al="urn:ietf:params:xml:ns:yang:ietf-alarms"/>
        <bbf-vdsl:vdsl xmlns:bbf-vdsl="urn:bbf:yang:bbf-vdsl"/>
        <bbf-xpongemtcont:xpongemtcont
xmlns:bbf-xpongemtcont="urn:bbf:yang:bbf-xpongemtcont"/>
        <sys:system xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system"/>
        <bbf-qos-plc-ep:envelope-profiles
xmlns:bbf-qos-plc-ep="urn:bbf:yang:bbf-qos-policer-envelope-profiles"/>
        <bbf-ghs:ghs xmlns:bbf-ghs="urn:bbf:yang:bbf-ghs"/>
        <if:interfaces
xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
        <bbf-qos-pol:policies
xmlns:bbf-qos-pol="urn:bbf:yang:bbf-qos-policies"/>
        <bbf-qos-tm:tm-profiles
xmlns:bbf-qos-tm="urn:bbf:yang:bbf-qos-traffic-mngt"/>
        <bbf-qos-plc:policing-profiles
xmlns:bbf-qos-plc="urn:bbf:yang:bbf-qos-policing"/>
        <bbf-selt:selt xmlns:bbf-selt="urn:bbf:yang:bbf-selt"/>
        <bbf-l2-d4r:l2-dhcpv4-relay-profiles
xmlns:bbf-l2-d4r="urn:bbf:yang:bbf-l2-dhcpv4-relay"/>
        <dot1x:nid-group
xmlns:dot1x="urn:ieee:std:802.1X:yang:ieee802-dot1x"/>
        *<nacm:nacm
xmlns:nacm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"/>*
        <bbf-hw-rpf-dpu:rpf
xmlns:bbf-hw-rpf-dpu="urn:bbf:yang:bbf-hardware-rpf-dpu"/>
        <bbf-pppoe-ia:pppoe-profiles
xmlns:bbf-pppoe-ia="urn:bbf:yang:bbf-pppoe-intermediate-agent"/>
        <bbf-fast:fast xmlns:bbf-fast="urn:bbf:yang:bbf-fast"/>
        <bbf-mgmd:multicast xmlns:bbf-mgmd="urn:bbf:yang:bbf-mgmd"/>
        <bbf-melt:melt xmlns:bbf-melt="urn:bbf:yang:bbf-melt"/>
        <bbf-subprof:subscriber-profiles
xmlns:bbf-subprof="urn:bbf:yang:bbf-subscriber-profiles"/>
        <bbf-ldra:dhcpv6-ldra-profiles
xmlns:bbf-ldra="urn:bbf:yang:bbf-ldra"/>
        <bbf-l2-fwd:forwarding
xmlns:bbf-l2-fwd="urn:bbf:yang:bbf-l2-forwarding"/>
      </config>
    </source>
  </copy-config>

netopeer2-server log. Note that at this point netopeer2-server is the only
sysrepo client.
[INF]: SR: Processing "/ietf-netconf:copy-config" "rpc" event with ID 1
priority 0 (remaining 1 subscribers).
[ERR]: SR: Access to the data model "ietf-netconf-server" is denied because
"igort" NACM authorization failed.
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 1
priority 0 (remaining 1 subscribers).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 4 event new RPC.
[INF]: NP: Session 1: thread 4 event reply error.

**Comment by michalvasko** [comment]
Hi,
it is correct then, you are effectively deleting all `ietf-netconf-server` configuration, which you do not have access to. And you can disable NACM but you must do so before this copy-config if it is to succeed (although I am not sure you really want to delete all `ietf-netconf-server` data, you will then not be able to connect by SSH). You just need to have
```xml
<nacm:nacm xmlns:nacm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
   <nacm:enable-nacm>false</nacm:enable-nacm>
</nacm:nacm>
```
in the config to disable NACM.

Regards,
Michal

**Comment by igortern** [comment]
Thank you Michal
